### ISSUE TITLE
SSD1306 - wrong character for "Degree" (167 instead of 248)

### ISSUE THREAD

**Issue by ber-red** [alfkoehn/CO2_monitor#2]
Aim: show the Degree sign in  "°C" 
Code:
In the .ino you reference to Codepage 437, character 167 (which is "Masculine ordinal indicator")
I found detail here: [codepage437](https://www.ascii-codes.com) and changed the section in  .ino to
```
...
display.setCursor(x0+7*6,15);
display.write(248);
...
```
PS: additionally I prefixed `display.write(248);` with 
`display.cp437(true);         // Use full 256 char 'Code Page 437' font`
(worked either with or whitout it but feels better)
 ;-)

**Comment by alfkoehn** [comment]
> Aim: show the Degree sign in "°C"
> Code:
> In the .ino you reference to Codepage 437, character 167 (which is "Masculine ordinal indicator")
> I found detail here: [codepage437](https://www.ascii-codes.com) and changed the section in .ino to
> 
> ```
> ...
> display.setCursor(x0+7*6,15);
> display.write(248);
> ...
> ```

indeed, I was using the wrong character, thanks for taking your time to post an issue here, greatly appreciated :)

 
> PS: additionally I prefixed `display.write(248);` with
> `display.cp437(true); // Use full 256 char 'Code Page 437' font`
> (worked either with or whitout it but feels better)

in my case, it was even necessary to do that, i.e. without enabling that font, the degree symbol is shown incorrectly.
